<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
	  
		<!-- Assembly Override Properties -->
		<PackageRequireLicenseAcceptance />
		<PackageId />
		<Version />
		<Authors />
		<Company />
		<Product />

		<Copyright />
		<PackageLicenseUrl />
		<PackageProjectUrl />
		<PackageIconUrl />
		<RepositoryUrl />
		<RepositoryType />
		<PackageTags />
		<PackageReleaseNotes />
		<NeutralLanguage />
		<AssemblyVersion />
		<FileVersion />
		<InformationalVersion />
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ProphetsWay.BaseDataAccess" Version="3.1.0" />
	</ItemGroup>


	
</Project>
